name: HackerNews
options:
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: com.ford.HackerNews
targets:
  HackerNews:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [HackerNews]
    scheme:
      testTargets:
        - HackerNewsTests
      gatherCoverageData: true
    dependencies:
      - carthage: Alamofire
      - carthage: SnapKit
      - carthage: PLOP
  HackerNewsTests:
    type: bundle.unit-test
    platform: iOS
    sources: [HackerNewsTests]