name: HackerNews
options:
  bundleIdPrefix: com.ford.HackerNews
targets:
  HackerNews:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [HackerNews]
    dependencies:
      - carthage: Alamofire
  HackerNewsTests:
    type: bundle.unit-test
    platform: iOS
    sources: [HackerNewsTests]